### ISSUE TITLE
Allow for combinations of display methods

### ISSUE THREAD

**Issue by kencinder** [steve4744/WhatIsThis#5]
We really prefer using the Boss Bar display for displaying the block you're looking at, with auto-display on, but it would be nice to be able to use say Crouch to display drops in chat or scoreboard in combination with using the Boss Bar normally.

So being able to define display conditions for a type would be useful, eg; something like the following

```
  bossbar:
    enabled: true
    condition: normal
    textcolor: WHITE
    barcolor: GREEN
```

```
  scoreboard:
    enabled: true
    condition: crouched
```

Condition could also cover using the right click item to have the display type only used if using the item
